name: baby_bloom_app
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  intl: 0.20.2
  flutter_switch: ^0.3.2
  carousel_slider: ^5.1.1
  lottie: ^3.3.1
  dotted_border: ^3.1.0
  syncfusion_flutter_charts: ^29.2.9
  flutter_calendar_carousel: ^2.5.4
  gradient_progress_bar: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#dependency_overrides:
#  intl: ^0.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/dark_images/

  fonts:
    - family: Outfit-Regular
      fonts:
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
    - family: Outfit-Medium
      fonts:
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
    - family: Outfit-SemiBold
      fonts:
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
    - family: Outfit-Bold
      fonts:
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
    - family: Outfit-ExtraBold
      fonts:
        - asset: assets/fonts/OutfitExtraBold.ttf
          weight: 800
    - family: Outfit-Black
      fonts:
        - asset: assets/fonts/OutfitBlack.ttf
          weight: 900

