name: mivi_screens_app
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  intl: 0.20.2
  flutter_switch: ^0.3.2
  carousel_slider: ^5.1.1
  dotted_border: ^3.1.0
  gradient_progress_bar: ^1.0.7
  fan_carousel_image_slider: ^1.3.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#dependency_overrides:
#  intl: ^0.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/dark_images/
    - assets/dark_icons/

  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

